spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mall_sms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 47.110.138.50:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000