spring:
  application:
    name: mall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mall_pms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000
#日志
logging:
  level:
    com.jinunn.mall: debug